$primary = rgb(d7c2bd)
$surface = rgb(151313)
$secondary = rgb(d0c4c1)
$error = rgb(ffb4ab)
$tertiary = rgb(cfc5b5)
$surface_lowest = rgb(0f0e0d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
