$primary = rgb(bbc7e1)
$surface = rgb(131315)
$secondary = rgb(c3c6d2)
$error = rgb(ffb4ab)
$tertiary = rgb(d4bfdc)
$surface_lowest = rgb(0e0e10)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
