color0 #131315
color1 #ffb4ab
color2 #bbc7e1
color3 #c3c6d2
color4 #d4bfdc
color5 #bbc7e1
color6 #c3c6d2
color7 #e4e2e4
color8 #8f9097
color9 #ffb4ab
color10 #bbc7e1
color11 #c3c6d2
color12 #d4bfdc
color13 #bbc7e1
color14 #c3c6d2
color15 #e4e2e4

cursor                #e4e2e4
cursor_text_color     #131315
background            #131315
foreground            #e4e2e4
selection_foreground  #c5c6cd
selection_background  #44474d
active_border_color   #bbc7e1
inactive_border_color #44474d
url_color             #bbc7e1

active_tab_foreground   #253145
active_tab_background   #bbc7e1
inactive_tab_foreground #c5c6cd
inactive_tab_background #44474d
cursor_trail_color      #c5c6cd
