color0 #151313
color1 #ffb4ab
color2 #d7c2bd
color3 #d0c4c1
color4 #cfc5b5
color5 #d7c2bd
color6 #d0c4c1
color7 #e7e1e0
color8 #9b8e8b
color9 #ffb4ab
color10 #d7c2bd
color11 #d0c4c1
color12 #cfc5b5
color13 #d7c2bd
color14 #d0c4c1
color15 #e7e1e0

cursor                #e7e1e0
cursor_text_color     #151313
background            #151313
foreground            #e7e1e0
selection_foreground  #d2c3c0
selection_background  #4e4542
active_border_color   #d7c2bd
inactive_border_color #4e4542
url_color             #d7c2bd

active_tab_foreground   #3a2d2a
active_tab_background   #d7c2bd
inactive_tab_foreground #d2c3c0
inactive_tab_background #4e4542
cursor_trail_color      #d2c3c0
